---
- hosts: all
  become: true
  tasks:

    - name: /etc/hosts configuration
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - "#Cluster Kubernetes"
        - "172.16.16.100 loadbalancer loadbalancer.example.com"
        - "172.16.16.101 kmaster1 kmaster1.example.com"
        - "172.16.16.102 kmaster2 kmaster2.example.com"
        - "172.16.16.201 kworker1 kworker1.example.com"

    - name: Make sure we have a 'wheel' groups
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
  
    - name: Add sudoers users to wheel group
      user:
        name="{{ item }}"
        groups=wheel
        append=yes
        state=present
        createhome=yes
        shell=/bin/bash
      with_items:
        - rreis
        - vagrant
    
    - name: Set up authorization keys for the rreis user
      authorized_key: user=rreis key="{{item}}"
      with_file:
        - /home/rreis/.ssh/id_rsa.pub

    - name: Disabling UFW
      ufw:
        state: disabled

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Creating a sysctl file with kubernetes network configuration content
      copy:
        dest: "/etc/sysctl.d/kubernetes.conf"
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
      register: result

    - name: Applying before configurations using sysctl
      shell: sysctl --system
      when: result.changed

    - name: Install some docker packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - software-properties-common
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - curl
        - vim
        - sysstat

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install docker and its dependecies
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce=5:19.03.10~3-0~ubuntu-focal
        - containerd.io
      notify:
        - docker status

    - name: Add rreis user to docker group
      user:
        name: rreis
        group: docker

    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubeadm=1.19.2-00
          - kubelet=1.19.2-00
          - kubectl=1.19.2-00

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --control-plane-endpoint="172.16.16.100:6443" --upload-certs --apiserver-advertise-address=172.16.16.101 --pod-network-cidr=192.168.0.0/16
      register: join_master_command
      when: (inventory_hostname == "kmaster1")
   
    - name: Install calico pod network
      become: yes
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml
      when: (inventory_hostname == "kmaster1")

    - name: Generate join command
      command: kubeadm token create --print-join-command-node
      register: join_command
      when: (inventory_hostname == "kmaster1")

    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command-node"
      when: (inventory_hostname == "kmaster1")

    - name: Copy join master command to local file
      become: false
      local_action: copy content="{{ join_master_command.stdout_lines }}" dest="./join-master-command"
      when: (inventory_hostname == "kmaster1")

    - name: Setup kubeconfig for root user
      command: "{{ item }}"
      when: (inventory_hostname == "kmaster1")
      with_items:
      - mkdir -p /root/.kube
      - cp -i /etc/kubernetes/admin.conf /root/.kube/config

  handlers:
    - name: docker status
      service: name=docker state=started